# The URL the site will be built for
base_url = "https://paperbytelogs.de/"
title = "Paper Byte Logs"
description = "A personal blog by jomaway"

generate_sitemap = true
generate_robots_txt = true

theme = "apollo"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true


generate_feeds = false

taxonomies = [
    { name = "tags" },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "gruvbox-dark"
# footnotes at the bottom
bottom_footnotes = true

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[extra]
# Put all your custom variables here
theme = "toggle"
comment = false

# logo_text = "Paper Byte Logs"
# author = "jomaway"
# accent_color = "blue"
socials = [
    { name = "github", url = "https://github.com/jomaway/", icon = "github" },
    { name = "mastodon", url = "https://fosstodon.org/@jomaway", icon = "mastodon" },
]

menu = [
  {name = "posts", url = "/posts", weight = 1},
  {name = "notes",  url = "/notes"},
  {name = "projects", url = "/projects"},
  # {name = "github", url = "https://github.com/jomaway", newtab = true},
]


[extra.analytics]
enabled = false
